#ifndef CAN_IDENTIFIERS_H
#define CAN_IDENTIFIERS_H

#define CAN_NO_MESSAGE_ID 0
#define CAN_JOYSTICK_MESSAGE_ID 1
#define CAN_TOUCH_MESSAGE_ID 2
#define CAN_SCORE_MESSAGE_ID 3
#define CAN_GAME_START_ID 4

#endif